name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ DOCKERHUB_USERNAME → rithi0 }}
        password: ${{ DOCKERHUB_TOKEN → dckr_pat_VfRIVtV2bDJk3_UufYsxwCQXMtw}}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: rithi0/nodejs-demo-app:latest
